# Generated by Django 6.0.5 on 2026-05-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='layout',
            field=models.CharField(default='vertical', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='col-span-3 row-span-1', max_length=50),
        ),
    ]
