# Generated by Django 6.0.5 on 2026-05-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_layout_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
