services:
  - type: web
    name: soapso
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      cd client && npm install && npm run build && cd ..
      pip install -r server/requirements.txt
      cd server && python manage.py migrate && python manage.py create_test_products --clear && python manage.py collectstatic --noinput && cd ..
    startCommand: cd server && gunicorn project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true